version: "3.8"
services:
    db:
        image: postgres:14.2
        volumes:
            - postgres_data:/var/lib/postgresql/data
        environment:
            POSTGRES_PASSWORD: root
            POSTGRES_USER: root
            POSTGRES_DB: hris
        ports:
            - "5432:5432"
        networks:
            - hris_network
        healthcheck:
            test: ["CMD", "pg_isready", "-U", "root"]
            interval: 10s
            timeout: 5s
            retries: 5

    # Frontend service
    frontend:
        build:
            context: ../../apps/frontend
            dockerfile: ../../infrastructure/docker/frontend/Dockerfile
        ports:
            - "3000:3000"
        depends_on:
            - backend
        networks:
            - hris_network
        restart: unless-stopped

    # Backend service
    backend:
        build:
            context: ../../apps/backend
            dockerfile: ../../infrastructure/docker/backend/Dockerfile
        volumes:
            - backend_storage:/var/www/html/storage
        depends_on:
            db:
                condition: service_healthy
        networks:
            - hris_network
        restart: unless-stopped
        environment:
            DB_CONNECTION: pgsql
            DB_HOST: db
            DB_PORT: 5432
            DB_DATABASE: hris
            DB_USERNAME: root
            DB_PASSWORD: root

    # Nginx service for backend
    nginx:
        image: nginx:alpine
        ports:
            - "80:80"
        volumes:
            - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
        depends_on:
            - backend
        networks:
            - hris_network

volumes:
    postgres_data:
    backend_storage:

networks:
    hris_network:
        driver: bridge
